### ISSUE TITLE
解压密码不对呀

### ISSUE THREAD

**Issue by kevinmore** [TrojanAZhen/BurpSuitePro-2.1#1]
burpsuite_pro_v2020.4.7z解压密码能再确认一下吗？

**Comment by kevinmore** [comment]
已解决，Mac上无法解压，但是放到Windows里就行了。

**Comment by attacker007** [comment]
Hi @TrojanAZhen  "Pany" Password is not working. Can you please check again !

Thanks.

**Comment by TrojanAZhen** [comment]
> ord is not workin

**is** `pany` **not** `Pany`
