### ISSUE TITLE
JDK版本为17, 启动 burp suite 报错

### ISSUE THREAD

**Issue by darkhorse007** [TrojanAZhen/BurpSuitePro-2.1#13]
现象:
运行
` java -noverify -javaagent:"/Applications/Burp Suite Professional.app/Contents/Resources/app/burp-loader-x-Ai.jar" -Xmx2048m -jar "/Applications/Burp Suite Professional.app/Contents/Resources/app/burpsuite_pro.jar"`
启动Burp Suite不成功, 弹出窗口, 信息如下:
To run Burp Suite using Java 17+, please supply the following JVM argument:
--add-opens=java.desktop/javax.swing=ALL-UNNAMED
--add-opens=java.base/java.lang=ALL-UNNAMED

通过更改命令:
`java -noverify -javaagent:"/Applications/Burp Suite Professional.app/Contents/Resources/app/burp-loader-x-Ai.jar" -Xmx2048m -jar --add-opens=java.desktop/javax.swing=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED "/Applications/Burp Suite Professional.app/Contents/Resources/app/burpsuite_pro.jar"`
再次运行, 顺利启动

**Comment by TrojanAZhen** [comment]
高版本的jdk/jre

**Comment by TrojanAZhen** [comment]
高版本的jdk/jre
