### ISSUE TITLE
upload 2020.6

### ISSUE THREAD

**Issue by x0rz4** [TrojanAZhen/BurpSuitePro-2.1#2]
https://mega.nz/file/WOoG2QQK#wvBqsNVkFMs0zMz6yec8GHNoMKAVLkl-JnVIG4gNDLg 
2020.6 pro的包
SHA256: 62ee276b92435599df9812f1399a5e82d090e39c8d322c5d2e3060cf2dc94542
MD5: 6f4a326f334d6b0c64a169d847305175

**Comment by TrojanAZhen** [comment]
**已更新，谢谢大佬的mega链接**

**Comment by TrojanAZhen** [comment]
> https://mega.nz/file/WOoG2QQK#wvBqsNVkFMs0zMz6yec8GHNoMKAVLkl-JnVIG4gNDLg
> 2020.6 pro的包
> SHA256
> ：62ee276b92435599df9812f1399a5e82d090e39c8d322c5d2e3060cf6dc6a4d3054f64a

**已更新，谢谢大佬的mega链接**
