### ISSUE TITLE
2020.7版本

### ISSUE THREAD

**Issue by TrojanAZhen** [TrojanAZhen/BurpSuitePro-2.1#3]
链接: https://pan.baidu.com/s/1xeD3EqKwcTuxCU_gDvSudA 提取码: duxx

解压密码在password.txt

**Comment by attacker007** [comment]
Hi @TrojanAZhen  Tried both links 

1. https://pan.baidu.com/s/1xeD3EqKwcTuxCU_gDvSudA (404 Status Code returned)
2. https://cloud.189.cn/t/E7fyIfuQRzu2 (Need account at 189.cn to download files)

Can you please upload the 2020.7 file on mega or gdrive?


Thanks

**Comment by TrojanAZhen** [comment]
> Hi @TrojanAZhen Tried both links
> 
> 1. https://pan.baidu.com/s/1xeD3EqKwcTuxCU_gDvSudA (404 Status Code returned)
> 2. https://cloud.189.cn/t/E7fyIfuQRzu2 (Need account at 189.cn to download files)
> 
> Can you please upload the 2020.7 file on mega or gdrive?
> 
> Thanks

**Mega: https://mega.nz/file/b94zzJSB#-gER_2ZVsRVfeoGRfdryNyKSZYFrv7ZaLQ8BKziMZIE**

**Comment by attacker007** [comment]
Hi @TrojanAZhen 

Thanks a lot.. I Never expected such quick response ! Thanks again

**Comment by attacker007** [comment]
Hi @TrojanAZhen Can you please tell me which java version is compatible with this loader? I've tried to run "burp-loader-keygen-2020_2_1.jar" file  but not able to execute this command on Java v8 & v13

```
java -noverify -Xbootclasspath/p:burp-loader-keygen-2020_2_1.jar -jar burpsuite_pro_v2020.7.jar

```

**Comment by TrojanAZhen** [comment]
> Hi @TrojanAZhen Can you please tell me which java version is compatible with this loader? I've tried to run "burp-loader-keygen-2020_2_1.jar" file but not able to execute this command on Java v8 & v13
> 
> ```
> java -noverify -Xbootclasspath/p:burp-loader-keygen-2020_2_1.jar -jar burpsuite_pro_v2020.7.jar
> ```

`burp-loader-keygen-2020_2_1.jar` **its just to crack the license**

> java 13.0.2

**u need to use** `burp-loader-x-Ai.jar` **to load burpsuite**

**burp-loader-x-Ai.jar must use java version 9-14, not support java8**

`java -noverify javaagent:burp-loader-x-Ai.jar -jar burpsuite_pro_v2020.7.jar`

> Demo

`java -noverify -javaagent:"C:\Program Files\BurpSuiteCommunity\burp-loader-x-Ai.jar" -Xmx2048m -jar "C:\Program Files\BurpSuiteCommunity\burpsuite_pro_v2020.7.jar"`

**Comment by attacker007** [comment]
Hi @TrojanAZhen 

"burp-loader-x-Ai.jar"  is giving Console Error as below:

![Screen Shot 2020-07-19 at 1 06 38 PM](https://user-images.githubusercontent.com/24765942/87870375-d99bed80-c9c0-11ea-8630-85e66795a81f.png)


I have installed Java v13.0.2 

![Screen Shot 2020-07-19 at 1 07 00 PM](https://user-images.githubusercontent.com/24765942/87870377-e587af80-c9c0-11ea-90b4-66f573e09ef6.png)

**Comment by TrojanAZhen** [comment]
> Hi @TrojanAZhen Can you please tell me which java version is compatible with this loader? I've tried to run "burp-loader-keygen-2020_2_1.jar" file but not able to execute this command on Java v8 & v13
> 
> ```
> java -noverify -Xbootclasspath/p:burp-loader-keygen-2020_2_1.jar -jar burpsuite_pro_v2020.7.jar
> ```

**u can select other java version** *or* **edit ur mac java config**

**Comment by TrojanAZhen** [comment]
> Hi @TrojanAZhen Can you please tell me which java version is compatible with this loader? I've tried to run "burp-loader-keygen-2020_2_1.jar" file but not able to execute this command on Java v8 & v13
> 
> ```
> java -noverify -Xbootclasspath/p:burp-loader-keygen-2020_2_1.jar -jar burpsuite_pro_v2020.7.jar
> ```

**i updated the en usage in README, u can see it**

**Comment by attacker007** [comment]
Hi @TrojanAZhen Do you have Fortify WebInspect in the uploads?
