### ISSUE TITLE
2020.8 pro

### ISSUE THREAD

**Issue by TrojanAZhen** [TrojanAZhen/BurpSuitePro-2.1#4]
> **Mega -Jar**

[https://mega.nz/file/fPJX3IbR#J25pLrhIz6wRrERhaoV8_2vqwrHEJmURGrzT-Vao2l8](https://mega.nz/file/fPJX3IbR#J25pLrhIz6wRrERhaoV8_2vqwrHEJmURGrzT-Vao2l8)

**Comment by attacker007** [comment]
Hi @TrojanAZhen  I am getting this Error when i try to run burp-loader-x-Ai.jar file . 

```

no main manifest attribute, in burp-loader-x-Ai.jar


```

**Comment by attacker007** [comment]
Hi @TrojanAZhen  please upload mega.nz  link for BurpSuitePro-2020.11.1

**Comment by TrojanAZhen** [comment]
> Hi @TrojanAZhen please upload mega.nz link for BurpSuitePro-2020.11.1

**[Mega](https://mega.nz/file/iw4glCJI#TTszy0qGvnffz0V-YCBhYw_9HhvARGO2AxK4IDgW4Y4)**

**Comment by attacker007** [comment]
Hi @TrojanAZhen  Please upload mega.nz link for BurpSuitePro-2020.11.2 

Thanks !!

**Comment by TrojanAZhen** [comment]
> Hi @TrojanAZhen Please upload mega.nz link for BurpSuitePro-2020.11.2
> 
> Thanks !!

**official download method has been updated，u can check the latest git README**
