### ISSUE TITLE
BurpSuite破解版在4K高分屏HiDPI上鼠标滑动选择文本错位的问题

### ISSUE THREAD

**Issue by lovelyjuice** [TrojanAZhen/BurpSuitePro-2.1#6]
### 测试过的环境
1. 屏幕分辨率4K，缩放225%以及250%
2. Windows 10 2004 和 1909
3. Burpsuite 2020.5 - 2020.8.1 + 本项目的BurpsuiteLoader
4. Oracle jdk8, jdk11, jdk14

### 问题描述
如下图，鼠标点击的位置与光标所在的位置不同，第一次点击时，鼠标位于 0 和 1 之间，光标却在 2 和 3 之间，点击后鼠标右滑选择文本，高亮显示选择的字符串为 34567890123，但通过复制粘贴得知实际选择的文本为 1234567890，也就是说显示的高亮的字符串和实际选择的字符串存在偏差。这个现象存在于 Proxy、Intruder、Repeater 等所有 HTTP Request&Response 编辑器中，测试发现4K屏存在问题，但2K屏没有问题。

![bs](https://user-images.githubusercontent.com/20644461/91421370-6ff8e400-e888-11ea-92f6-3fe8b2c6e335.gif)

![bs1](https://user-images.githubusercontent.com/20644461/91421425-83a44a80-e888-11ea-8cfc-3859d21065bc.gif)

### 尝试解决
更换jdk，更改jdk dpi设置，调整系统缩放比例，更换burpsuite版本，更新Windows均无法解决上述问题，除非缩放调到100%，但对于4k屏来说100%会导致字体过小，得不偿失。无意中发现官方的社区版一直没有这个问题，因此怀疑是破解版才有的缺陷。

### 暂时的解决办法
更改 java.exe 的高DPI设置，将其设为“系统” 或者 “系统（增强）”，缺点就是界面会变得比较模糊，就像没有适配高分屏的软件一样。

![image](https://user-images.githubusercontent.com/20644461/91421235-42139f80-e888-11ea-97bf-e72e8be3281f.png)

### 寻找热心的有钱人士
由于没有条件(qian)对官方pro正版进行测试，也无法完全确定是破解导致的缺陷，发起这个issue的目的是为了让其他人看到后，能够少走一些弯路，当然如果哪位热心人士有条件的话也可以测试一下 官方pro版 和 破解的pro版 在4K屏上的显示差异。

**Comment by TrojanAZhen** [comment]
> 适配高分屏

**官方pro jar包，校验过sha256和md5，其次x-AI大佬的loader没做混淆，有能力的可以自行围观。。。**

**Comment by lovelyjuice** [comment]
把两个项目弄混了。。。抱歉

**Comment by lovelyjuice** [comment]
12月23日更新，原仓库已被DMCA屏蔽。宋体字体大小设为4的整数倍比如16号，consolas字体设为18号即可解决上述问题，同时不会变糊。测试的版本是2020.12.1，该方法对pro版和社区版均有效。
![image](https://user-images.githubusercontent.com/20644461/102987555-799c0b00-454d-11eb-8978-2a2cdf8fa132.png)
