### ISSUE TITLE
有汉化包吗？

### ISSUE THREAD

**Issue by billgege123** [TrojanAZhen/BurpSuitePro-2.1#7]
你好，能处理一下汉化吗？

**Comment by TrojanAZhen** [comment]
> **汉化请参照** [BurpSuiteCn](https://github.com/hackxx/BurpSuiteCn)

> **天翼云的网盘有汉化包**

**Comment by TrojanAZhen** [comment]
> 你好，能处理一下汉化吗？

> **汉化请参照** [BurpSuiteCn](https://github.com/hackxx/BurpSuiteCn)

> **天翼云的网盘有汉化包**

**Comment by Z-fly** [comment]
现在汉化没了？
