### ISSUE TITLE
现在是不能激活了吗？我的一直激活失败，open-jak11和14都试了(Linux下)

### ISSUE THREAD

**Issue by wxs211** [TrojanAZhen/BurpSuitePro-2.1#8]
![image](https://user-images.githubusercontent.com/61727188/98311283-ff014580-2009-11eb-9eed-c044a0a84cd8.png)

**Comment by TrojanAZhen** [comment]
@wxs211 **我在新debian环境下用open-jdk14再次测试了一下，可用，附截图，请自行排查 命令 jdk jar包等问题**
![微信截图_20201106165006](https://user-images.githubusercontent.com/15818542/98346407-e0726d00-2050-11eb-82d0-b801f8b37126.png)
![微信截图_20201106165021](https://user-images.githubusercontent.com/15818542/98346433-ec5e2f00-2050-11eb-8131-c41cc104bb2f.png)
![微信截图_20201106165046](https://user-images.githubusercontent.com/15818542/98346475-fbdd7800-2050-11eb-8201-c4946c8bf1ec.png)

**Comment by wxs211** [comment]
> @wxs211 **我在新debian环境下用open-jdk14再次测试了一下，可用，附截图，请自行排查 命令 jdk jar包等问题**
> ![微信截图_20201106165006](https://user-images.githubusercontent.com/15818542/98346407-e0726d00-2050-11eb-82d0-b801f8b37126.png)
> ![微信截图_20201106165021](https://user-images.githubusercontent.com/15818542/98346433-ec5e2f00-2050-11eb-8131-c41cc104bb2f.png)
> ![微信截图_20201106165046](https://user-images.githubusercontent.com/15818542/98346475-fbdd7800-2050-11eb-8201-c4946c8bf1ec.png)

一定要放在/opt下吗?

**Comment by wxs211** [comment]
> @wxs211 **我在新debian环境下用open-jdk14再次测试了一下，可用，附截图，请自行排查 命令 jdk jar包等问题**
> ![微信截图_20201106165006](https://user-images.githubusercontent.com/15818542/98346407-e0726d00-2050-11eb-82d0-b801f8b37126.png)
> ![微信截图_20201106165021](https://user-images.githubusercontent.com/15818542/98346433-ec5e2f00-2050-11eb-8131-c41cc104bb2f.png)
> ![微信截图_20201106165046](https://user-images.githubusercontent.com/15818542/98346475-fbdd7800-2050-11eb-8201-c4946c8bf1ec.png)

我把jdk那些彻底删了重新装了一下就好了，谢谢！
